[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "socket"
    version = "@project.version@"
    path = "../socket-native/build/libs/socket-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["socket"]

    [[platform.libraries]]
    artifactId = "socket"
    version = "@project.version@"
    path = "../socket-test-utils/build/libs/socket-test-utils-@project.version@.jar"
    groupId = "org.ballerinalang.stdlib.socket"
    modules = ["socket"]
